### ISSUE TITLE
Issues running geopip_test.py in Ubuntu

### ISSUE THREAD

**Issue by ArtPoon** [yzhai220/geopip#2]
Members of my lab @jpalme56 and @Abayomi-Olabode have run into some issues attempting to run this test script.  
First:
```console
Traceback (most recent call last):
  File "geopip_test.py", line 71, in <module>
    piProb = pi_from_qmat(qMat)
  File "/home/art/git/geopip/src/pip_util.py", line 20, in pi_from_qmat
    qMatExt = np.hstack([qMat, np.ones((qMatDim, 1.0))])
  File "/home/art/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 203, in ones
    a = empty(shape, dtype, order)
TypeError: 'float' object cannot be interpreted as an index
```
We fixed this by modifying line 20 in `src/pip_util.py`:
```python
        qMatExt = np.hstack([qMat, np.ones((qMatDim, 1))])
```

Next problem:
```console
/home/art/git/geopip/src/pip_util.py:23: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  res = np.linalg.lstsq(qMatExt.T, b)
Traceback (most recent call last):
  File "geopip_test.py", line 99, in <module>
    seqs, alignInSeg, alignsSeg, segRateDict, bDict, multiAlignSeqs, lenSegs = leaf_data_from_sim_tree(treeTrue)
  File "/home/art/git/geopip/src/geopip_sim.py", line 201, in leaf_data_from_sim_tree
    pdm = treemeasure.PatristicDistanceMatrix(treeTem)
AttributeError: 'module' object has no attribute 'PatristicDistanceMatrix'
```

I am currently reproducing and working through these issues with @jpalme56 on my workstation (Ubuntu 18.04, Python 2.7.15rc1, R 3.4.4).

**Comment by ArtPoon** [comment]
Running `dendropy` 4.4.0.  It has a typo where `PatristicDistanceMatrix` has been replaced with `PatrisiticDistanceMatrix`.  Will inform package maintainer.

**Comment by ArtPoon** [comment]
Binaries provided with repo under `/software` are not compatible with my system.  Replaced with binaries that I happened to have in my `/usr/local/bin` directory.  Ran through test script up to this point:
```
### updating rate matrix Q ###

Exception in thread "main" java.lang.RuntimeException: ma.newick.ParseException: Encountered " ":" ": "" at line 1, column 178.
Was expecting:
    ")" ...
    
	at pty.RootedTree$Util.load(RootedTree.java:240)
```
skipping some java spam
```
Traceback (most recent call last):
  File "geopip_test.py", line 142, in <module>
    qMatCTMC1, bDictCTMC1, treeCTMC1, nllkCTMC1 = opt_ctmc_full(qMatStart, multiAlign, javaDirectory, modelDirectory, eStepFile, parametersPath, inputLoc, outputLoc, dataLoc, execsLoc, rFileLoc, cList, qRates=[1.], suffix='_ctmc_1rate', updateQ=updateQ, tol=1.e-2, bTol=1.e-3, iterMax=100)
  File "/home/art/git/geopip/src/ctmc_est.py", line 95, in opt_ctmc_full
    qMatNew, piProbNew = opt_qmat_em_full(qMat, cList, inputLoc, outputLoc, javaDirectory, modelDirectory, eStepFile, parametersPath, execsLoc)
  File "/home/art/git/geopip/src/pip_est.py", line 213, in opt_qmat_em_full
    llh = llh_from_llhfiles(llhFiles)
  File "/home/art/git/geopip/src/io_json.py", line 454, in llh_from_llhfiles
    fileTem = open(llhFile)
IOError: [Errno 2] No such file or directory: '/home/art/git/geopip/result/geopip_test/runs/5/output/all/llh.txt'
```

**Comment by ArtPoon** [comment]
Problematic Java call is:
```console
java -Xmx8g -cp  /home/art/git/geopip/software/java/legacy/bin:/home/art/git/geopip/software/java/jars/aws-java-sdk-flow-build-tools-1.6.0.jar:/home/art/git/geopip/software/java/jars/servlet-api.jar:/home/art/git/geopip/software/java/jars/lucene-core-3.3.0.jar:/home/art/git/geopip/software/java/jars/gson-2.2.4-javadoc.jar:/home/art/git/geopip/software/java/jars/jsci-core.jar:/home/art/git/geopip/software/java/jars/mvel2-2.1.3.Final.jar:/home/art/git/geopip/software/java/jars/aws-java-sdk-1.6.0-javadoc.jar:/home/art/git/geopip/software/java/jars/pdfbox-app-1.8.0.jar:/home/art/git/geopip/software/java/jars/javaml-0.1.5.jar:/home/art/git/geopip/software/java/jars/guava-15.0.jar:/home/art/git/geopip/software/java/jars/ninja.jar:/home/art/git/geopip/software/java/jars/Jama-1.0.2.jar:/home/art/git/geopip/software/java/jars/aws-java-sdk-1.6.0.jar:/home/art/git/geopip/software/java/jars/forester.jar:/home/art/git/geopip/software/java/jars/jblas-1.2.3.jar:/home/art/git/geopip/software/java/jars/aws-java-sdk-1.6.0-sources.jar:/home/art/git/geopip/software/java/jars/deployment-javaee-full.jar:/home/art/git/geopip/software/java/jars/commons-cli-1.0.jar:/home/art/git/geopip/software/java/jars/gson-2.2.4-sources.jar:/home/art/git/geopip/software/java/jars/commons-math-2.2.jar:/home/art/git/geopip/software/java/jars/gson-2.2.4.jar:/home/art/git/geopip/software/java/jars/gson-2.2.2.jar:/home/art/git/geopip/software/java/jars/opencsv-2.2.jar conifer.ml.ComputePosteriorMain -treeFile /home/art/git/geopip/result/geopip_test/runs/10/input/all.tree.txt -alignmentFile /home/art/git/geopip/result/geopip_test/runs/10/input/all.align.txt -parametersPath /home/art/git/geopip/result/geopip_test/runs/10/input.json -branchOutput /home/art/git/geopip/result/geopip_test/runs/10/output/all -rootOutput /home/art/git/geopip/result/geopip_test/runs/10/output/all/root.txt -likelihood /home/art/git/geopip/result/geopip_test/runs/10/output/all/llh.txt -outputCTMCStatistics true
```

Newick tree string is:
```console
art@orolo:~/git/geopip/script$ cat /home/art/git/geopip/result/geopip_test/runs/10/input/all.tree.txt 
(((seq7:0.1093172022,seq8:0.1743106198):0.1301275116,(seq5:0.1568744242,seq6:0.05864739505):0.2642988999):0.1616350254,((seq3:0.1821900275,seq4:1e-10):0.1391104487,seq1:0.1132822064):0.05237149651,seq2:0.03429266396);
```

**Comment by ArtPoon** [comment]
Switching from JDK 11 to JDK 8 seems to have resolved the above problem.  Next issue:
```console
Restricted nSites: 272 -> 272
-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /tmp/jblas6589445315227428250libjblas_arch_flavor.so: libgfortran.so.3: cannot open shared object file: No such file or directory.
```
Followed instructions and installed `libgfortran3` with `apt` package manager.
This seems to have resolved the problem, closing issue.
